apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: implementor-secrets
  namespace: iris-ui
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "<implementor-wi-client-id>"
    keyvaultName: "<keyvault-name>"
    tenantId: "<tenant-id>"
    objects: |
      array:
        - |
          objectName: github-app-id
          objectType: secret
        - |
          objectName: github-app-installation-id
          objectType: secret
        - |
          objectName: github-app-private-key
          objectType: secret
        - |
          objectName: copilot-pat
          objectType: secret
        - |
          objectName: figma-pat
          objectType: secret
  secretObjects:
    - secretName: implementor-secrets
      type: Opaque
      data:
        - objectName: github-app-id
          key: github-app-id
        - objectName: github-app-installation-id
          key: github-app-installation-id
        - objectName: github-app-private-key
          key: github-app-private-key
        - objectName: copilot-pat
          key: copilot-pat
        - objectName: figma-pat
          key: figma-pat
