apiVersion: v1
kind: ServiceAccount
metadata:
  name: implementor
  namespace: iris-ui
  annotations:
    azure.workload.identity/client-id: "<implementor-wi-client-id>"
  labels:
    azure.workload.identity/use: "true"
